### ISSUE TITLE
`imm` without any parameter should probably print help

### ISSUE THREAD

**Issue by KunalSaini** [jci-metasys/powershell-metasysrestclient#40]
currently it just does nothing.

~\Documents\proj\> imm
~\Documents\proj\>

**Comment by michaelgwelch** [comment]
> currently it just does nothing.

Wow, that's actually pretty incredible that instead of blowing up it just does nothing. That's actually quite impressive. :smile:

**Comment by michaelgwelch** [comment]
As of the current version 2.3-rc1 it'll prompt you for the required parameters which is idiomatic powershell. I guess in powershell you are meant to use `help imm` for help.
